name: Docker

on:
  release:
    types: created

  push:
    branches:
      - master
      - develop
      - '*'

  pull_request:

env:
  DOCKERHUB_ORG: kooper
  MASTER_REPO: robkooper/clowder

jobs:
  docker:        
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        name:
          - clowder
          - toolserver
          - mongo-init
          - monitor
          - check
        include:
          - name: clowder
            FOLDER: "."
            IMAGE: clowder
            README: README.md
          - name: toolserver
            FOLDER: scripts/toollaunchservice
            IMAGE: toolserver
            README: ""
          - name: mongo-init
            FOLDER: scripts/mongo-init
            IMAGE: mongo-init
            README: ""
          - name: monitor
            FOLDER: scripts/monitor
            IMAGE: monitor
            README: ""
          - name: check
            FOLDER: scripts/check
            IMAGE: check
            README: ""
    steps:
      - uses: actions/checkout@v2
      # - name: Build image
      #   run: |
      #     docker build \
      #       --build-arg BRANCH=${{ github.ref }} \
      #       --build-arg VERSION=${{ github.run_number }} \
      #       --build-arg BUILDNUMBER=${{ github.run_number }} \
      #       --build-arg GITSHA1=${{ github.sha  }} \
      #       --tag image ${{ matrix.FOLDER }}

      # - name: Publish to Docker Hub
      #   #if: github.event_name != 'pull_request' && github.repository == 'clowder-framework/clowder'
      #   if: github.event_name != 'pull_request' && github.repository == ${{ env.MASTER_REPO }}
      #   uses: elgohr/Publish-Docker-Github-Action@2.14
      #   env:
      #     BRANCH: ${{ github.ref }}
      #     VERSION: ${{ github.run_number }}
      #     BUILDNUMBER: ${{ github.run_number }}
      #     GITSHA1: ${{ github.sha  }}
      #   with:
      #     name: ${{ env.DOCKERHUB_ORG }}/${{ matrix.IMAGE }}
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #     context: ${{ matrix.FOLDER }}
      #     tag_semver: true
      #     tag_names: true
      #     buildargs: BRANCH,VERSION,BUILDNUMBER,GITSHA1

      - name: check file
        id: filecheck
        run: |
          if [ "${{ matrix.README }}" != "" -a -e "${{ matrix.README }}" ]; then
            echo "##[set-output name=exists;]true"  
          else
            echo "##[set-output name=exists;]false"
          fi
      - name: Docker Hub Description
        if: steps.filecheck.outputs.exists == true && github.event_name != 'pull_request' && github.repository == env.MASTER_REPO
        run: |
          echo ${{ steps.filecheck.outputs.exists }}
          echo ${{ github.event_name }}
          echo ${{ github.repository }}
          echo ${{ env.MASTER_REPO }}
      - name: Docker Hub Description
        run: |
          echo ${{ steps.filecheck.outputs.exists }}
          echo ${{ github.event_name }}
          echo ${{ github.repository }}
          echo ${{ env.MASTER_REPO }}

        # uses: peter-evans/dockerhub-description@v2
        # env:
        #   DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        #   DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        #   DOCKERHUB_REPOSITORY: ${{ env.DOCKERHUB_ORG }}/${{ matrix.IMAGE }}
        #   README_FILEPATH: ${{ matrix.README }}

      # - name: Publish to GitHub
      #   if: github.event_name != 'pull_request'
      #   uses: elgohr/Publish-Docker-Github-Action@2.14
      #   env:
      #     BRANCH: ${{ github.ref }}
      #     VERSION: ${{ github.run_number }}
      #     BUILDNUMBER: ${{ github.run_number }}
      #     GITSHA1: ${{ github.sha  }}
      #   with:
      #     name: ${{ github.actor }}/clowder/${{ matrix.IMAGE }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     context: ${{ matrix.FOLDER }}
      #     tag_semver: true
      #     tag_names: true
      #     registry: docker.pkg.github.com
      #     buildargs: BRANCH,VERSION,BUILDNUMBER,GITSHA1
