name: Docker

on:
  release:
    types: created

  push:
    branches:
      - master
      - develop
      - '*'

  pull_request:

jobs:

  docker:        
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        name:
          - clowder
          - toolserver
          - mongo-init
          - monitor
          - check
        include:
          - name: clowder
            FOLDER: "."
            IMAGE: clowder
          - name: toolserver
            FOLDER: scripts/toollaunchservice
            IMAGE: toolserver
          - name: mongo-init
            FOLDER: scripts/mongo-init
            IMAGE: mongo-init
          - name: monitor
            FOLDER: scripts/monitor
            IMAGE: monitor
          - name: check
            FOLDER: scripts/check
            IMAGE: check
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build \
            --build-arg BRANCH=${{ github.ref }} \
            --build-arg VERSION=${{ github.run_number }} \
            --build-arg BUILDNUMBER=${{ github.run_number }} \
            --build-arg GITSHA1=${{ github.sha  }} \
            --tag image ${{ matrix.FOLDER }}

      - name: Publish to Docker Hub
        #if: github.event_name != 'pull_request' && github.repository == 'clowder-framework/clowder'
        if: github.event_name != 'pull_request' && github.repository == 'robkooper/clowder'
        uses: elgohr/Publish-Docker-Github-Action@2.14
        env:
          BRANCH: ${{ github.ref }}
          VERSION: ${{ github.run_number }}
          BUILDNUMBER: ${{ github.run_number }}
          GITSHA1: ${{ github.sha  }}
        with:
          name: kooper/${{ matrix.IMAGE }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          context: ${{ matrix.FOLDER }}
          tag_semver: true
          tag_names: true
          buildargs: BRANCH,VERSION,BUILDNUMBER,GITSHA1

      - name: Publish to GitHub
        if: github.event_name != 'pull_request'
        uses: elgohr/Publish-Docker-Github-Action@2.14
        env:
          BRANCH: ${{ github.ref }}
          VERSION: ${{ github.run_number }}
          BUILDNUMBER: ${{ github.run_number }}
          GITSHA1: ${{ github.sha  }}
        with:
          name: ${{ github.actor }}/clowder/${{ matrix.IMAGE }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ matrix.FOLDER }}
          tag_semver: true
          tag_names: true
          registry: docker.pkg.github.com
          buildargs: BRANCH,VERSION,BUILDNUMBER,GITSHA1
