name: Release

on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'

jobs:
  release:
    if: github.repository == 'clowder-framework/clowder'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        name:
          - clowder
          - toolserver
          - mongo-init
          - monitor
          - check
        include:
          - name: clowder
            FOLDER: "."
            IMAGE: clowder
          - name: toolserver
            FOLDER: scripts/toollaunchservice
            IMAGE: toolserver
          - name: mongo-init
            FOLDER: scripts/mongo-init
            IMAGE: mongo-init
          - name: monitor
            FOLDER: scripts/monitor
            IMAGE: monitor
          - name: check
            FOLDER: scripts/check
            IMAGE: check
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          BRANCH: ${{ github.ref }}
          VERSION: ${{ github.run_number }}
          BUILDNUMBER: ${{ github.run_number }}
          GITSHA1: ${{ github.sha  }}
        with:
          name: kooper/${{ matrix.IMAGE }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          context: ${{ matrix.FOLDER }}
          tag_semver: true
          buildargs: BRANCH,VERSION,BUILDNUMBER,GITSHA1
      - name: Publish to GitHub
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          BRANCH: ${{ github.ref }}
          VERSION: ${{ github.run_number }}
          BUILDNUMBER: ${{ github.run_number }}
          GITSHA1: ${{ github.sha  }}
        with:
          name: ${{ github.actor }}/clowder/${{ matrix.IMAGE }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ matrix.FOLDER }}
          tag_semver: true
          registry: docker.pkg.github.com
          buildargs: BRANCH,VERSION,BUILDNUMBER,GITSHA1

