name: Release

on:
  release:

# TODO check on release and https://github.com/marketplace/actions/upload-to-release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: show env
        run: env

